apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-t3iv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0028-tenant/ci10t-786-0028-app/devfile-sample-t3iv@sha256:c7f22994899818c1edd8802a6fd37ae056a6e67c00df174d85a75a5937fed802
        name: my-nodejs
        resources: {}
status: {}
